/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Telas;
import Classes.*;

/**
 *
 * @author eduar
 */

import Classes.Controle;
import Classes.Veterinario;
import javax.swing.JOptionPane;
public class GerenciarProfissional extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarProfissional.class.getName());
    Controle controle;
    /**
     * Creates new form FormVeterinario
     */
    public GerenciarProfissional(java.awt.Frame parent, boolean modal, Controle controle) {
        super(parent, modal);
        
        this.controle = controle;
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnExcluir = new javax.swing.JButton();
        btnEdiatr = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        rbVeterinario = new javax.swing.JRadioButton();
        rbRecepcionista = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnExcluir.setText("EXCLUIR");

        btnEdiatr.setText("EDITAR");
        btnEdiatr.addActionListener(this::btnEdiatrActionPerformed);

        btnListar.setText("LISTAR");

        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        buttonGroup1.add(rbVeterinario);
        rbVeterinario.setSelected(true);
        rbVeterinario.setText("Veterinário");

        buttonGroup1.add(rbRecepcionista);
        rbRecepcionista.setText("Recepcionaista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdiatr, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdiatr, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbVeterinario)
                .addGap(21, 21, 21)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
                
        if(rbVeterinario.isSelected()){
            AdicionarVeterinario adicionarVeterinario = new AdicionarVeterinario(this, true, controle);
            adicionarVeterinario.setVisible(true);
        }else{
            AdicionarRecepcionista adicionarVeterinario = new AdicionarRecepcionista(this, true, controle);
            adicionarVeterinario.setVisible(true);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEdiatrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdiatrActionPerformed
        String cod = JOptionPane.showInputDialog("Código: ");
        
        if (cod == null) return;
        
        if (cod.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "E necessario um Código para pesquisar!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int codigo = Integer.parseInt(cod);
            
            Profissional aux = controle.buscarProfissional(codigo);
            
            if (rbVeterinario.isSelected()){
                if (aux != null && aux instanceof Veterinario){
                    EditarVeterinario editarVeterinario = new EditarVeterinario(this, true, controle, (Veterinario)aux);
                    editarVeterinario.setVisible(true);
                }
            }else {
                if (aux != null && aux instanceof Recepcionista){
                    EditarRecepcionista editarRecepcionista = new EditarRecepcionista(this, true, controle, (Recepcionista)aux);
                    editarRecepcionista.setVisible(true);
                }
            }
        
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Codigo so pode conter numeros.");
        }
    }//GEN-LAST:event_btnEdiatrActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEdiatr;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnListar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rbRecepcionista;
    private javax.swing.JRadioButton rbVeterinario;
    // End of variables declaration//GEN-END:variables
}
